FROM python:3.11-slim

WORKDIR /app
ENV PIP_NO_CACHE_DIR=1 PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

COPY dashboard.py /app/dashboard.py

RUN pip install --upgrade pip && \
    pip install streamlit requests matplotlib pandas

EXPOSE 8501
ENV API_URL=http://api:8000

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]